apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/component: service
    {{- include "waylon.commonLabels" . | nindent 4 }}
    {{- with .Values.web.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.web.service.annotations }}
  annotations:
    {{- toYaml .Values.web.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - port: {{ .Values.web.service.port }}
    targetPort: 9292
    protocol: TCP
    name: waylon
  selector:
    app.kubernetes.io/component: web
    {{- include "waylon.commonLabels" . | nindent 4 }}
  