apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/component: web
    {{- include "waylon.commonLabels" . | nindent 4 }}
    {{- with .Values.web.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.web.deployment.annotations }}
  annotations:
    {{- toYaml .Values.web.deployment.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.web.deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.web.deployment.maxSurge }}
      maxUnavailable: {{ .Values.web.deployment.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      {{- include "waylon.commonLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/component: web
        {{- include "waylon.commonLabels" . | nindent 8 }}
    spec:
      {{- if .Values.common.strictSecurity }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      {{- end }}
      {{- if .Values.common.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.common.imagePullSecret }}
      {{- end }}
      volumes:
      - name: tmpvol
        emptyDir: {}
      containers:
      - name: web
        image: {{ .Values.common.waylonImage }}
        imagePullPolicy: {{ .Values.web.deployment.imagePullPolicy }}
        stdin: true
        tty: true
        args: ["web"]
        env:
        - name: REDIS
          value: {{ .Values.redis.hostAndPort }}
        - name: LOG_LEVEL
          value: {{ .Values.web.deployment.logLevel }}
        envFrom:
        - secretRef:
            name: waylon-secret
        resources:
          limits:
            memory: {{ .Values.web.deployment.memoryLimit }}
            cpu: {{ .Values.web.deployment.cpuLimit }}
          requests:
            memory: 64Mi
            cpu: 10m
        livenessProbe:
          tcpSocket:
            port: waylon
          timeoutSeconds: 2
          initialDelaySeconds: 2
          periodSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: waylon
          timeoutSeconds: 6
          initialDelaySeconds: 2
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - name: waylon
          containerPort: 9292
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp
          name: tmpvol
        {{- if .Values.common.strictSecurity }}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
        {{- end }}
